config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "messages#index"
  resources :users, only: [:edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %title ChatSpace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/notifications'
    = yield

app/views/messages/_main_chat.html.haml
.chat-main
 .Right-header
  .Right-header__left-box
   .Right-header__left-box__group-name
    group
   %ul.Right-header__left-box__menber-list
    member : 
    %li.Right-header__left-box__menber-list__member
     name
  = link_to '#' do
   .Right-header__right-box
    Edit
 .MessageList
  .Message
   .Message__info
    .Message__info__name
     test000
    .Message__info__date
     2020/06/28(Sun) 22:00:00
   .Message__text
    こんにちは！
  .Message
   .Message__info
    .Message__info__name
     test001
    .Message__info__date
     2020/06/28(Sun) 22:05:09
   .Message__text
    こんばんは
  ＜チャット画面＞
 .Footer
  %form.new-message
   .input-box
    %input.input-box-text{type: 'text', placeholder: 'type a message'}
    %label.image
     = icon('far', 'image', class: '')
     %input.Hidden{type: 'file'}
   %input.Send-btn{type: 'submit', value: 'Send'}

app/views/messages/_side_bar.html.haml
.SideBar
 .Left-header
  .Left-header__box
   
   %h3.Left-header__userName
    = current_user.name
   .Left-header__iconBox
    .Left-header__icon
     = link_to '#' do
      = icon('fas', 'edit')
    .Left-header__icon
     = link_to edit_user_path(current_user) do
      = icon('fas', 'cog')

 .GroupList
  .Group
   .Group__group-name
    <グループ>
   .Group__last-message
    message

app/views/messages/index.html.haml
.Wrapper
  = render "side_bar"
  = render "main_chat"

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'